environment: prod

replicaCount: 3

image:
  tag: "v1.0.0"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

database:
  enabled: true
  host: "microservice-prod.cluster-xyz.us-west-2.rds.amazonaws.com"
  passwordSecret:
    name: "microservice-prod-db-password"
    key: "password"

cache:
  enabled: true
  host: "microservice-prod.abc123.cache.amazonaws.com"

messageQueue:
  enabled: true
  queueUrl: "https://sqs.us-west-2.amazonaws.com/123456789/microservice-prod-queue"

ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:123456789:certificate/prod-cert"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  hosts:
    - host: "api.company.com"
      paths:
        - path: /microservice
          pathType: Prefix
  tls:
    - secretName: microservice-tls
      hosts:
        - api.company.com

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

podDisruptionBudget:
  enabled: true
  minAvailable: 2

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - microservice-chart
      topologyKey: kubernetes.io/hostname

nodeSelector:
  node-type: "production"

tolerations:
- key: "production"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"