{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  # Default configuration
  LOG_LEVEL: "info"
  METRICS_ENABLED: "{{ .Values.features.enableMetrics }}"
  TRACING_ENABLED: "{{ .Values.features.enableTracing }}"
  LOGGING_ENABLED: "{{ .Values.features.enableLogging }}"
{{- end }}